#: kivy 1.11.1

<Num_1>
	text : '1'
<Num_2>
	text : '2'
<Num_3>
	text : '3'
<Num_4>
	text : '4'
<Num_5>
	text : '5'
<Num_6>
	text : '6'
<Num_7>
	text : '7'
<Num_8>
	text : '8'
<Num_9>
	text : '9'
<Num_0>
	text : '0'
<Num_00>
	text : '00'

<Dot>
	text: '.'

<Add_btn>
	text : '+'
<Multi_btn>
	text : '*'
<Sub_btn>
	text : '-'
<Div_btn>
	text : '/'


<Equal_btn>
	text : '='
<Clear_btn>
	text : 'Clear'
<Del_btn>
	text : 'Del'